//! Cross-validates this crate's independent, hand-rolled decoder against
//! containers encoded by the already round-trip-tested Node prototype (see
//! `fixtures.rs`, generated by `node prototype/scripts/gen-rust-fixtures.js`)
//! — catching the class of bug a single implementation checking itself
//! against itself never can.

use super::fixtures::*;
use super::*;

const WIFI_KNOWN_KEYS: &[i64] = &[0, 1, 2, 4];

#[test]
fn wifi_record_routes_and_fields_extract() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");

    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("no odd keys here")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let ssid = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"My Coffee Shop");
    let password = find_value(rec.map_bytes, 2).unwrap().unwrap();
    assert_eq!(read_definite_string(password).unwrap(), b"guest123");
}

#[test]
fn a_64_bit_class_private_use_type_id_decodes_correctly() {
    let container = Container::parse(LARGE_TYPE_ID_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].type_id(), Some(Key::Uint(u64::MAX)));
    assert!(!records[0].ignored);
}

#[test]
fn unrecognized_even_key_aborts_the_record() {
    let container = Container::parse(WIFI_UNKNOWN_EVEN_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("must not reach an odd key")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Aborted(6));
}

#[test]
fn unrecognized_odd_key_is_silently_ignored() {
    let container = Container::parse(WIFI_UNKNOWN_ODD_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];

    let mut ignored = Vec::new();
    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| ignored.push(k)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);
    assert_eq!(ignored, vec![7]);

    let ssid = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"SSID");
}

#[test]
fn a_record_with_no_typeid_is_ignored() {
    let container = Container::parse(NO_TYPEID_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(rec.ignored);
    assert_eq!(rec.type_id(), None);
}

#[test]
fn one_aborted_record_does_not_affect_its_sibling() {
    let container = Container::parse(TWO_RECORD_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 2);

    let first = check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |_| {}).unwrap();
    assert_eq!(first, CriticalityOutcome::Aborted(6));

    assert_eq!(records[1].type_id(), Some(Key::Uint(900)));
    assert!(!records[1].ignored);
    let payload = find_value(records[1].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(payload).unwrap(), b"sibling record");
}

#[test]
fn ndef_path_bare_sequence_with_no_magic_still_routes() {
    // Own-URI-scheme carriers never carry magic or a discriminator -- built
    // directly via encodeRecordBytes, not by stripping magic off a full
    // container (which would now leave the discriminator item behind).
    let bare_seq = BARE_SEQUENCE_NO_DISCRIMINATOR;
    assert!(
        Container::parse(bare_seq).is_err(),
        "must not look like a valid magic-prefixed container"
    );

    let records: Vec<_> = records_from_sequence(bare_seq)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
}

#[test]
fn bad_magic_is_rejected() {
    let mut bad_magic = WIFI_CONTAINER.to_vec();
    bad_magic[0] = 0x00;
    assert_eq!(Container::parse(&bad_magic).err(), Some(Error::BadMagic));
}

// ---------------------------------------------------------------------
// §3.2's field-value-shape rule was dropped: a field value may now be
// any well-formed CBOR item, not just a flat scalar or definite-length
// string. field_value_shape_rule_rejects_a_bare_array_even_under_an_odd_
// optional_key, tag_24_directly_wrapping_another_tag_is_rejected_not_
// silently_walked, and a_real_tag_whose_own_definition_requires_array_
// content_is_still_rejected all previously asserted DisallowedFieldValue
// Shape errors for exactly these three shapes -- inverted below, since
// all three are legal now. skip_value's stricter domain was merged into
// skip_any_item's (docs/FINDINGS.md).
// ---------------------------------------------------------------------

#[test]
fn a_bare_array_field_value_is_legal_now_previously_disallowed_outright() {
    let container = Container::parse(ARRAY_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    // find_value/read_definite_string only handle the simple scalar/
    // string case by design (docs on read_definite_string) -- confirm the
    // raw bytes are at least present and well-formed-CBOR-shaped (a
    // 3-element array: 0x83 0x01 0x02 0x03), without decoding them
    // further (that needs a real CBOR library, same as any nested
    // container always did).
    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(raw, &[0x83, 0x01, 0x02, 0x03]);
}

#[test]
fn structured_content_is_carried_as_an_opaque_byte_string_and_skips_at_zero_cost() {
    let container = Container::parse(BYTE_STRING_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    let nested_cbor = read_definite_string(raw).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn tag_24_wrapping_a_definite_length_string_directly_is_a_legal_field_value() {
    let container = Container::parse(TAG24_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(&raw[..2], &[0xd8, 0x18]);
    let nested_cbor = read_definite_string(&raw[2..]).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn a_tag_directly_wrapping_another_tag_is_legal_now_previously_disallowed() {
    let container = Container::parse(NESTED_TAG24_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    // tag 24 (0xd8 0x18) wrapping tag 24 (0xd8 0x18) wrapping the real
    // definite-length byte string -- confirm it's present and well-formed
    // without decoding further.
    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(&raw[..4], &[0xd8, 0x18, 0xd8, 0x18]);
}

#[test]
fn any_tag_number_is_allowed_when_its_content_is_a_definite_length_string() {
    let container = Container::parse(OTHER_TAG_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(raw[0], 0xc0); // tag 0
    let date_string = read_definite_string(&raw[1..]).unwrap();
    assert_eq!(date_string, b"2026-07-10T12:00:00Z");
}

#[test]
fn a_tag_wrapping_array_content_is_legal_now_previously_rejected_regardless_of_the_real_tag_definition(
) {
    let container = Container::parse(STRUCTURED_TAG_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    // tag 4 (0xc4) wrapping a 2-element array [-2, 27315] (0x82 0x21 0x19
    // 0x6a b3) -- confirm it's present and well-formed without decoding
    // further.
    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(raw[0], 0xc4);
    assert_eq!(raw[1], 0x82); // 2-element array
}

#[test]
fn container_discriminator_needs_no_interpretation_from_this_crate() {
    let container = Container::parse(HEADER_CONTAINER).expect("valid container");

    // This crate exposes the discriminator's raw bytes (including its own
    // CBOR head byte) and nothing more -- no namespace/hint parsing lives
    // here, that's an optional, Record-Type-interpretation-layer concern
    // (header.js in the Node prototype). Just confirm it's exactly the
    // 8-byte decentralized namespace value the fixture encodes (0x48 =
    // major type 2, length 8), split off correctly.
    assert_eq!(
        container.discriminator(),
        &[0x48, 0xa9, 0xd6, 0xe1, 0xf3, 0x0b, 0x7c, 0x44, 0x82]
    );

    // And the Records iterator starts from the *real* first Record,
    // completely unaffected by whatever the discriminator's own shape
    // was -- the same generic decoder, no discriminator-specific code
    // path in how Records themselves get routed and walked.
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
    assert!(!records[0].ignored);
    let ssid = find_value(records[0].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"SSID");
}

// ---------------------------------------------------------------------
// Decentralized (byte-string) Type IDs and backup typeIDs were both
// retired (docs/FINDINGS.md) -- byte_string_type_id_routes_correctly and
// backup_type_ids_are_accumulated_and_accessible previously asserted the
// old behavior; replaced below with tests confirming both shapes now
// degrade gracefully instead.
// ---------------------------------------------------------------------

#[test]
fn a_byte_string_typeid_is_no_longer_recognized_the_record_is_unroutable() {
    let container =
        Container::parse(BYTE_STRING_TYPE_ID_UNRECOGNIZED_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(rec.ignored);
    assert_eq!(rec.type_id(), None);
}

#[test]
fn a_second_typeid_shaped_item_is_not_accumulated_as_a_backup_it_is_silently_skipped() {
    // There is no forward-compat padding left between typeId and the
    // map: payload now accepts any well-formed CBOR shape (§3.1/§3.2),
    // so a bare uint immediately after typeId -- with no map before it
    // -- is unconditionally this Record's payload, not a skipped stray
    // item.
    let container =
        Container::parse(SECOND_TYPE_ID_NOT_ACCUMULATED_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    assert_eq!(rec.map_bytes, &[] as &[u8]);
    assert_eq!(read_uint(rec.payload().unwrap()).unwrap(), 900);
}

#[test]
fn namespace_prefix_yields_the_typeid_and_the_raw_namespace() {
    let container = Container::parse(NAMESPACE_PAIRING_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(!rec.ignored);

    // The namespace's own typeId becomes the routing typeId, exactly as
    // if it had been a bare prefix item -- routing doesn't care which
    // form produced it.
    assert_eq!(rec.type_id(), Some(Key::Uint(1)));

    // The leading byte string is exposed raw, uninterpreted -- this
    // crate doesn't know it's "a namespace," just that a byte string
    // immediately followed by a valid typeId is this shape.
    match rec.local_namespace() {
        Some(Key::ByteString(bytes)) => assert_eq!(bytes, &[0xcd, 0xcd, 0xcd, 0xcd]),
        other => panic!("expected ByteString local_namespace, got {:?}", other),
    }
}

#[test]
fn a_uint_where_a_namespace_was_intended_is_read_directly_as_the_typeid_instead() {
    // Namespace recognition requires the array's first element to be a
    // byte string; a uint there is unconditionally valid typeID shape on
    // its own, so there is no "malformed namespace" state left over --
    // it's simply this Record's typeID (100), and the originally-
    // intended typeID (1) becomes a skipped stray item.
    let container =
        Container::parse(UINT_NAMESPACE_SLOT_UNRECOGNIZED_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    assert_eq!(rec.local_namespace(), None);
}

#[test]
fn a_record_with_no_pairing_item_has_no_local_namespace() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records[0].local_namespace(), None);
}

#[test]
fn namespace_pairing_stacks_with_a_map_and_a_real_present_payload() {
    // Not just "payload is absent" -- proves Rust's decoder actually
    // extracts a *present* payload's real bytes correctly, cross-
    // validated against a Node-encoded fixture, stacked with a namespace
    // override and an ordinary field map on the same Record.
    let container =
        Container::parse(NAMESPACE_PAIRING_WITH_PAYLOAD_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert_eq!(rec.type_id(), Some(Key::Uint(1)));
    assert!(rec.local_namespace().is_some());

    let field = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(field).unwrap(), b"field, not payload");

    let payload = rec.payload().expect("payload must be present");
    assert_eq!(
        read_definite_string(payload).unwrap(),
        b"real payload bytes"
    );
}

// ---------------------------------------------------------------------
// Payload slot (§3.1): any well-formed CBOR item following the field
// map -- the same shape rule field values already have (§3.2),
// including another Record. `payload()` exposes the raw encoded item
// bytes, uninterpreted; `read_definite_string`/`read_uint`/
// `payload_as_record` peel off a specific expected shape. The NDEF-ID-
// equivalent that previously occupied this position was removed; the
// slot now carries opaque or plaintext content for wrapper records and
// media.
// ---------------------------------------------------------------------

#[test]
fn a_record_with_a_plain_map_and_no_payload_has_payload_absent() {
    let container = Container::parse(PLAIN_MAP_ONLY_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    assert_eq!(rec.payload(), None);
}

#[test]
fn a_record_with_no_payload_has_it_absent_zero_cost_when_unused() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records[0].payload(), None);
}

#[test]
fn a_present_payload_with_no_map_at_all_is_recognized_directly_after_typeid() {
    // The shipped Wrapper-Record shape (e.g. Compress: `[8, h'...']`) --
    // no map, because there was nothing else to put in one. Proves the
    // item right after typeId is read as payload, not skipped as an
    // unrecognized forward-compat item, when no map precedes it.
    let container = Container::parse(PAYLOAD_ONLY_NO_MAP_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(8)));
    assert_eq!(rec.map_bytes, &[] as &[u8]);
    assert_eq!(
        read_definite_string(rec.payload().unwrap()).unwrap(),
        b"deflate-style opaque bytes"
    );
}

#[test]
fn map_payload_and_subrecords_all_present_on_the_same_record_the_full_grammar_at_once() {
    // Each piece (map, payload, subrecords) has its own dedicated test
    // elsewhere; this proves the full `[typeId, map, payload, subrecord*]`
    // shape parses correctly together, not just each piece in isolation --
    // the shipped Wrapper-plus-Media-Preview-subrecord pattern (§4.5).
    let container =
        Container::parse(MAP_PAYLOAD_AND_SUBRECORDS_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(8)));

    let field = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(
        read_definite_string(field).unwrap(),
        b"not the compress key -- just an ordinary field"
    );
    assert_eq!(
        read_definite_string(rec.payload().unwrap()).unwrap(),
        b"deflate-style opaque bytes"
    );

    let subrecords: Vec<_> = rec.subrecords().unwrap().collect::<Result<_, _>>().unwrap();
    assert_eq!(subrecords.len(), 1);
    assert_eq!(subrecords[0].type_id(), Some(Key::Uint(14)));
    let media_type = find_value(subrecords[0].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(media_type).unwrap(), b"image/png");
}

#[test]
fn an_indefinite_length_payload_is_not_recognized_here_documented_node_divergence() {
    // A conformant encoder never emits this (§3.4 requires definite-length
    // forms), but a decoder MAY still encounter one. rust/qdef-core
    // deliberately does NOT recognize it as payload (explicit
    // !is_indefinite() guard) -- it falls through to subrecord-scanning,
    // where it's skipped again as a non-array item, same as any other
    // forward-compat item this crate doesn't understand. The Node
    // prototype DOES recognize this shape (its `cbor` library normalizes
    // indefinite-length strings before application code sees them); both
    // are conformant per §3.1's decoder-tolerance wording -- only a
    // conformant encoder's own (always definite-length) output is
    // required to round-trip identically everywhere.
    //
    // array(2) [ typeID uint(20), indefinite-length byte string "hello" ]
    const BYTES: &[u8] = &[0x82, 0x14, 0x5f, 0x45, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0xff];
    let mut records = records_from_sequence(BYTES);
    let rec = records.next().unwrap().unwrap();
    assert_eq!(rec.type_id(), Some(Key::Uint(20)));
    assert_eq!(rec.payload(), None);
}

// ---------------------------------------------------------------------
// Negative-integer map keys. CBOR permits them generally and QDEF's spec
// never explicitly restricted map keys to non-negative uints. Bytes
// generated from the Node prototype via an inline script, not
// `gen-rust-fixtures.js`, since this is EXPERIMENTAL and not part of the
// committed fixture set. See docs/FINDINGS.md.
// ---------------------------------------------------------------------

/// `[typeId(100), { 0: "SSID", -1: "wifi-record-1" }]`
const RECORD_WITH_NEG_KEY: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x20, 0x6d, 0x77, 0x69, 0x66, 0x69,
    0x2d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2d, 0x31,
];

/// RECORD_WITH_NEG_KEY immediately followed by a second, ordinary Record
/// (`[typeId(200), { 0: "second" }]`) -- proves the Sequence survives
/// past the negative-keyed Record, not just that Record in isolation.
const TWO_RECORD_SEQ_WITH_NEG_KEY: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x20, 0x6d, 0x77, 0x69, 0x66, 0x69,
    0x2d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2d, 0x31, 0x82, 0x18, 0xc8, 0xa1, 0x00, 0x66, 0x73,
    0x65, 0x63, 0x6f, 0x6e, 0x64,
];

#[test]
fn a_negative_map_key_no_longer_hard_errors_the_whole_record() {
    let records: Vec<_> = records_from_sequence(RECORD_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records.len(), 1);
    assert!(!records[0].ignored);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
}

#[test]
fn a_negative_map_key_no_longer_kills_decoding_of_sibling_records_in_the_same_sequence() {
    let records: Vec<_> = records_from_sequence(TWO_RECORD_SEQ_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .expect("both records parse; a negint key must not abort the Sequence");
    assert_eq!(records.len(), 2);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
    assert_eq!(records[1].type_id(), Some(Key::Uint(200)));
}

#[test]
fn check_criticality_treats_an_unrecognized_odd_negative_key_the_same_as_an_odd_positive_one() {
    // -1 is odd (§3.6's Common Field Key tier reuses the same even/odd
    // rule §3.2 already gives positive keys) -- unrecognized, it's
    // silently ignored, not skipped without a trace and not aborted.
    let records: Vec<_> = records_from_sequence(RECORD_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    let mut ignored = Vec::new();
    let outcome =
        check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |k| ignored.push(k)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);
    assert_eq!(ignored, vec![-1]);
}

/// Four fixtures pinning the raw-CBOR-argument-to-actual-value parity
/// table directly: `Key::NegInt` carries the *raw argument* (RFC 8949
/// §3.1: actual value is `-1 - arg`), which has the *inverse* parity of
/// the argument itself. Each is `[typeId(100), { 0: "SSID", <key>: "a" }]`
/// with `<key>` encoded at CBOR argument 0/1/2/3 respectively (heads
/// 0x20/0x21/0x22/0x23) -- bytes generated from the Node prototype via
/// an inline script, not `gen-rust-fixtures.js` (same EXPERIMENTAL
/// status as `RECORD_WITH_NEG_KEY` above).
const RECORD_WITH_NEG_KEY_ARG0_VALUE_NEG1_ODD: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x20, 0x61, 0x61,
];
const RECORD_WITH_NEG_KEY_ARG1_VALUE_NEG2_EVEN: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x21, 0x61, 0x61,
];
const RECORD_WITH_NEG_KEY_ARG2_VALUE_NEG3_ODD: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x22, 0x61, 0x61,
];
const RECORD_WITH_NEG_KEY_ARG3_VALUE_NEG4_EVEN: &[u8] = &[
    0x82, 0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x23, 0x61, 0x61,
];

#[test]
fn negint_arg_to_value_parity_table_is_computed_correctly_not_just_the_raw_args_own_parity() {
    let cases: &[(&[u8], i64, bool)] = &[
        // (fixture, actual key value, is the value even/critical?)
        (RECORD_WITH_NEG_KEY_ARG0_VALUE_NEG1_ODD, -1, false),
        (RECORD_WITH_NEG_KEY_ARG1_VALUE_NEG2_EVEN, -2, true),
        (RECORD_WITH_NEG_KEY_ARG2_VALUE_NEG3_ODD, -3, false),
        (RECORD_WITH_NEG_KEY_ARG3_VALUE_NEG4_EVEN, -4, true),
    ];
    for &(bytes, value, is_even) in cases {
        let records: Vec<_> = records_from_sequence(bytes)
            .collect::<Result<_, _>>()
            .unwrap();
        let mut ignored = Vec::new();
        let outcome =
            check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |k| ignored.push(k)).unwrap();
        if is_even {
            assert_eq!(
                outcome,
                CriticalityOutcome::Aborted(value),
                "arg encoding for value {value} must abort (even/critical)"
            );
        } else {
            assert_eq!(
                outcome,
                CriticalityOutcome::Ok,
                "arg encoding for value {value} must not abort (odd/optional)"
            );
            assert_eq!(ignored, vec![value]);
        }
    }
}

// ---------------------------------------------------------------------
// Indefinite-length (chunked) byte/text strings inside field values.
// Hand-constructed (RFC 8949's deterministic/canonical encoding never
// produces indefinite-length forms, so the Node prototype's
// `cbor.encodeCanonical` can't generate this fixture -- there is nothing
// for gen-rust-fixtures.js to cross-validate against here).
// ---------------------------------------------------------------------

/// `[typeId(100), { 0: (indefinite text string) "SSID" chunked as "SS"+"ID" }]`
/// 0x7f = indefinite-length text string start; 0x62 "SS"; 0x62 "ID"; 0xff = break.
const RECORD_WITH_INDEFINITE_STRING_VALUE: &[u8] = &[
    0x82, 0x18, 0x64, 0xa1, 0x00, 0x7f, 0x62, 0x53, 0x53, 0x62, 0x49, 0x44, 0xff,
];

/// Same shape, but a chunk's major type doesn't match the string's own
/// (a byte-string chunk inside a text-string sequence) -- malformed.
const RECORD_WITH_MISMATCHED_CHUNK_MAJOR_TYPE: &[u8] =
    &[0x82, 0x18, 0x64, 0xa1, 0x00, 0x7f, 0x42, 0x53, 0x53, 0xff];

#[test]
fn an_indefinite_length_chunked_string_field_value_is_now_skip_safe() {
    let records: Vec<_> = records_from_sequence(RECORD_WITH_INDEFINITE_STRING_VALUE)
        .collect::<Result<_, _>>()
        .expect("indefinite-length string field values are legal now");
    assert_eq!(records.len(), 1);
    assert!(!records[0].ignored);

    // find_value/skip_any_item correctly find where the chunked string
    // ends (right after the break byte) -- confirmed by the fact parsing
    // succeeded and the map has no trailing garbage. read_definite_string
    // deliberately does NOT handle indefinite-length strings (see its own
    // docs) -- reading the concatenated content back needs a real CBOR
    // library, same as any other exotic shape.
    let raw = find_value(records[0].map_bytes, 0).unwrap().unwrap();
    assert_eq!(raw, &[0x7f, 0x62, 0x53, 0x53, 0x62, 0x49, 0x44, 0xff]);
}

#[test]
fn a_malformed_indefinite_string_chunk_sequence_is_rejected_not_silently_walked() {
    let result: Result<Vec<_>, _> =
        records_from_sequence(RECORD_WITH_MISMATCHED_CHUNK_MAJOR_TYPE).collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::MalformedIndefiniteString))
    );
}

// ---------------------------------------------------------------------
// Subrecords (§3.1's generalized `ID[]{}` shape): every Record is now
// exactly one self-delimited CBOR array; everything past its own field
// Map, for the rest of that array, is itself a nested Record, parsed
// with the exact same Record grammar as the top-level Sequence (the
// same `Records` iterator, reused recursively via `Record::subrecords`)
// -- not a new grammar. Resolves the TagDrop Media Preview/Payload
// correlation problem without relying on Record position, and replaces
// the earlier `ID[]{}`-with-one-optional-array design (superseded once
// every Record became array-wrapped). See docs/DESIGN.md and
// docs/FINDINGS.md.
// ---------------------------------------------------------------------

#[test]
fn a_subrecord_round_trips_dispatched_by_its_own_typeid() {
    let container = Container::parse(SUBRECORDS_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let outer = &records[0];
    assert_eq!(outer.type_id(), Some(Key::Uint(20)));

    let subs: Vec<_> = outer
        .subrecords()
        .expect("subrecords present")
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(subs.len(), 1);
    assert_eq!(subs[0].type_id(), Some(Key::Uint(2)));
    let payload = find_value(subs[0].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(payload).unwrap(), b"fragment");
}

#[test]
fn a_record_with_no_subrecords_has_them_absent_zero_cost_when_unused() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert!(records[0].subrecords().is_none());
}

#[test]
fn a_subrecord_can_itself_carry_a_namespace_and_its_own_further_subrecords() {
    let container = Container::parse(SUBRECORDS_WITH_NAMESPACE_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let outer = &records[0];
    assert_eq!(outer.type_id(), Some(Key::Uint(21)));

    let subs: Vec<_> = outer
        .subrecords()
        .unwrap()
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(subs.len(), 1);
    let inner = &subs[0];
    assert_eq!(inner.type_id(), Some(Key::Uint(1)));
    match inner.local_namespace() {
        Some(Key::ByteString(bytes)) => assert_eq!(bytes, &[0xcd, 0xcd, 0xcd, 0xcd]),
        other => panic!("expected ByteString local_namespace, got {:?}", other),
    }

    let leaf: Vec<_> = inner
        .subrecords()
        .expect("nested subrecords present")
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(leaf.len(), 1);
    assert_eq!(leaf[0].type_id(), Some(Key::Uint(22)));
}

#[test]
fn every_record_is_self_bounded_a_record_with_subrecords_never_bleeds_into_its_sibling() {
    let container = Container::parse(SUBRECORDS_SIBLING_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 2);

    assert_eq!(records[0].type_id(), Some(Key::Uint(23)));
    assert_eq!(records[0].subrecords().unwrap().count(), 1);

    assert_eq!(records[1].type_id(), Some(Key::Uint(1)));
    assert!(records[1].subrecords().is_none());
    match records[1].local_namespace() {
        Some(Key::ByteString(bytes)) => assert_eq!(bytes, &[0xcd, 0xcd, 0xcd, 0xcd]),
        other => panic!("expected ByteString local_namespace, got {:?}", other),
    }
}

/// `[typeId(24), { 0: "parent payload" }, null, [{ 0: "no typeid here" }]]`
/// -- the explicit `null` marks "no real payload, subrecords follow"
/// (§3.1's mandatory placeholder; an array directly here, with no
/// marker, would instead be read as a record-shaped payload). The
/// trailing subrecord slot holds a well-formed CBOR array whose own
/// first (and only) element is a bare map, with nothing namespace/
/// typeId-shaped before it: well-formed CBOR, invalid Record grammar.
/// Hand-constructed (not via gen-rust-fixtures.js, which has no direct
/// way to encode a malformed subrecord).
const RECORD_WITH_MALFORMED_SUBRECORD: &[u8] = &[
    0x84, 0x18, 0x18, 0xa1, 0x00, 0x6e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x20, 0x70, 0x61, 0x79,
    0x6c, 0x6f, 0x61, 0x64, 0xf6, 0x81, 0xa1, 0x00, 0x6e, 0x6e, 0x6f, 0x20, 0x74, 0x79, 0x70, 0x65,
    0x69, 0x64, 0x20, 0x68, 0x65, 0x72, 0x65,
];

/// `[typeId(1), { 0: "sibling payload" }]` immediately following
/// RECORD_WITH_MALFORMED_SUBRECORD in the same Sequence.
const SIBLING_AFTER_MALFORMED_SUBRECORD: &[u8] = &[
    0x82, 0x01, 0xa1, 0x00, 0x6f, 0x73, 0x69, 0x62, 0x6c, 0x69, 0x6e, 0x67, 0x20, 0x70, 0x61, 0x79,
    0x6c, 0x6f, 0x61, 0x64,
];

#[test]
fn a_malformed_subrecord_does_not_corrupt_its_parent_or_any_sibling_top_level_record() {
    // Each Record's own array boundary is generic (skip_any_item, purely
    // well-formedness-based) and independent of whether its contents
    // parse as valid Record grammar -- so the outer Sequence walker can
    // always find the next sibling, and a malformed subrecord surfaces
    // as that one subrecord being `ignored`, not a hard failure.
    let mut buf = RECORD_WITH_MALFORMED_SUBRECORD.to_vec();
    buf.extend_from_slice(SIBLING_AFTER_MALFORMED_SUBRECORD);

    let records: Vec<_> = records_from_sequence(&buf)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records.len(), 2);

    assert_eq!(records[0].type_id(), Some(Key::Uint(24)));
    let subs: Vec<_> = records[0]
        .subrecords()
        .expect("subrecord slot present")
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(subs.len(), 1);
    assert!(subs[0].ignored);

    assert_eq!(records[1].type_id(), Some(Key::Uint(1)));
    let payload = find_value(records[1].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(payload).unwrap(), b"sibling payload");
}

// ---------------------------------------------------------------------
// Payload's generalized shape rule (§3.1/§3.2): any well-formed CBOR
// item, not just byte/text string -- including another Record (major
// type 4), decoded recursively via `payload_as_record`. A map-shaped
// payload needs the field Map explicitly present, since major type 5
// right after typeId is otherwise always the field Map.
// ---------------------------------------------------------------------

#[test]
fn a_record_shaped_payload_is_decoded_recursively_via_payload_as_record() {
    let container = Container::parse(RECORD_SHAPED_PAYLOAD_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert_eq!(rec.type_id(), Some(Key::Uint(14)));
    assert!(rec.subrecords().is_none());

    let nested = rec
        .payload_as_record()
        .expect("payload is array-shaped")
        .expect("valid nested Record");
    assert_eq!(nested.type_id(), Some(Key::Uint(6)));
    let media_type = find_value(nested.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(media_type).unwrap(), b"image/png");
    assert_eq!(
        read_definite_string(nested.payload().unwrap()).unwrap(),
        b"jpeg bytes"
    );
}

#[test]
fn a_byte_string_payload_is_not_record_shaped() {
    let container = Container::parse(PAYLOAD_ONLY_NO_MAP_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert!(records[0].payload_as_record().is_none());
}

#[test]
fn a_map_shaped_payload_with_no_other_fields_gets_an_explicit_empty_field_map() {
    let container =
        Container::parse(MAP_SHAPED_PAYLOAD_NO_FIELDS_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert_eq!(rec.type_id(), Some(Key::Uint(20)));
    // The field Map is present but empty -- not absent -- disambiguating
    // it from the map-shaped payload that follows.
    assert_eq!(rec.map_bytes, &[0xa0][..]);

    let payload = rec.payload().expect("payload present");
    assert_eq!(payload[0] >> 5, 5, "payload's own major type is map (5)");
}

#[test]
fn payload_as_record_nests_to_depth_2() {
    let container =
        Container::parse(NESTED_PAYLOAD_AS_RECORD_DEPTH2_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let outer = &records[0];
    assert_eq!(outer.type_id(), Some(Key::Uint(30)));

    let middle = outer
        .payload_as_record()
        .expect("outer payload is array-shaped")
        .expect("valid nested Record");
    assert_eq!(middle.type_id(), Some(Key::Uint(31)));

    let inner = middle
        .payload_as_record()
        .expect("middle payload is array-shaped")
        .expect("valid nested Record");
    assert_eq!(inner.type_id(), Some(Key::Uint(32)));
    assert_eq!(
        read_definite_string(inner.payload().unwrap()).unwrap(),
        b"innermost bytes"
    );
}

/// `[20, { 0: "image/png" }, [6, { 0: "image/png" }], [7, { 0: "extra" }]]`
/// -- MISSING the mandatory `null` placeholder before what was intended
/// as two subrecords. Hand-constructed (not via gen-rust-fixtures.js,
/// which always emits a correct encoder's output) to demonstrate what a
/// hand-crafter's mistake actually decodes to.
const TWO_INTENDED_SUBRECORDS_MISSING_NULL_MARKER: &[u8] = &[
    0x84, 0x14, 0xa1, 0x00, 0x69, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6e, 0x67, 0x82, 0x06,
    0xa1, 0x00, 0x69, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6e, 0x67, 0x82, 0x07, 0xa1, 0x00,
    0x65, 0x65, 0x78, 0x74, 0x72, 0x61,
];

#[test]
fn gotcha_a_missing_null_marker_silently_reads_the_first_intended_subrecord_as_payload_instead() {
    // Not an error -- a different, well-formed, spec-mandated
    // interpretation (§3.1): the first array right after the Map is
    // always the payload when non-null, never subrecord 0. A hand-
    // crafter who forgets the marker loses their first subrecord this
    // way, silently, not via a decode failure.
    let mut records = records_from_sequence(TWO_INTENDED_SUBRECORDS_MISSING_NULL_MARKER);
    let rec = records.next().unwrap().unwrap();
    assert_eq!(rec.type_id(), Some(Key::Uint(20)));

    let payload_as_record = rec
        .payload_as_record()
        .expect("payload is array-shaped")
        .expect("valid nested Record");
    assert_eq!(payload_as_record.type_id(), Some(Key::Uint(6)));

    let subs: Vec<_> = rec
        .subrecords()
        .expect("one subrecord slot remains")
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(subs.len(), 1);
    assert_eq!(subs[0].type_id(), Some(Key::Uint(7)));
}
