//! Cross-validates this crate's independent, hand-rolled decoder against
//! containers encoded by the already round-trip-tested Node prototype (see
//! `fixtures.rs`, generated by `node prototype/scripts/gen-rust-fixtures.js`)
//! — catching the class of bug a single implementation checking itself
//! against itself never can.

use super::fixtures::*;
use super::*;

const WIFI_KNOWN_KEYS: &[u64] = &[0, 1, 2, 4];

#[test]
fn wifi_record_routes_and_fields_extract() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");

    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("no odd keys here")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let ssid = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"My Coffee Shop");
    let password = find_value(rec.map_bytes, 2).unwrap().unwrap();
    assert_eq!(read_definite_string(password).unwrap(), b"guest123");
}

#[test]
fn a_64_bit_class_private_use_type_id_decodes_correctly() {
    let container = Container::parse(LARGE_TYPE_ID_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].type_id(), Some(Key::Uint(u64::MAX)));
    assert!(!records[0].ignored);
}

#[test]
fn unrecognized_even_key_aborts_the_record() {
    let container = Container::parse(WIFI_UNKNOWN_EVEN_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("must not reach an odd key")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Aborted(6));
}

#[test]
fn unrecognized_odd_key_is_silently_ignored() {
    let container = Container::parse(WIFI_UNKNOWN_ODD_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];

    let mut ignored = Vec::new();
    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| ignored.push(k)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);
    assert_eq!(ignored, vec![7]);

    let ssid = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"SSID");
}

#[test]
fn a_record_with_no_typeid_is_ignored() {
    let container = Container::parse(NO_TYPEID_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(rec.ignored);
    assert_eq!(rec.type_id(), None);
}

#[test]
fn one_aborted_record_does_not_affect_its_sibling() {
    let container = Container::parse(TWO_RECORD_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 2);

    let first = check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |_| {}).unwrap();
    assert_eq!(first, CriticalityOutcome::Aborted(6));

    assert_eq!(records[1].type_id(), Some(Key::Uint(900)));
    assert!(!records[1].ignored);
    let payload = find_value(records[1].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(payload).unwrap(), b"sibling record");
}

#[test]
fn ndef_path_bare_sequence_with_no_magic_still_routes() {
    // Own-URI-scheme carriers never carry magic or a discriminator -- built
    // directly via encodeRecordBytes, not by stripping magic off a full
    // container (which would now leave the discriminator item behind).
    let bare_seq = BARE_SEQUENCE_NO_DISCRIMINATOR;
    assert!(
        Container::parse(bare_seq).is_err(),
        "must not look like a valid magic-prefixed container"
    );

    let records: Vec<_> = records_from_sequence(bare_seq)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
}

#[test]
fn bad_magic_is_rejected() {
    let mut bad_magic = WIFI_CONTAINER.to_vec();
    bad_magic[0] = 0x00;
    assert_eq!(Container::parse(&bad_magic).err(), Some(Error::BadMagic));
}

#[test]
fn field_value_shape_rule_rejects_a_bare_array_even_under_an_odd_optional_key() {
    let container = Container::parse(DISALLOWED_ARRAY_VALUE_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}

#[test]
fn structured_content_is_carried_as_an_opaque_byte_string_and_skips_at_zero_cost() {
    let container = Container::parse(BYTE_STRING_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    let nested_cbor = read_definite_string(raw).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn tag_24_wrapping_a_definite_length_string_directly_is_a_legal_field_value() {
    let container = Container::parse(TAG24_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(&raw[..2], &[0xd8, 0x18]);
    let nested_cbor = read_definite_string(&raw[2..]).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn tag_24_directly_wrapping_another_tag_is_rejected_not_silently_walked() {
    let container = Container::parse(NESTED_TAG24_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}

#[test]
fn any_tag_number_is_allowed_when_its_content_is_a_definite_length_string() {
    let container = Container::parse(OTHER_TAG_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 9)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 9).unwrap().unwrap();
    assert_eq!(raw[0], 0xc0); // tag 0
    let date_string = read_definite_string(&raw[1..]).unwrap();
    assert_eq!(date_string, b"2026-07-10T12:00:00Z");
}

#[test]
fn a_real_tag_whose_own_definition_requires_array_content_is_still_rejected() {
    let container = Container::parse(STRUCTURED_TAG_WRAPPED_VALUE_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}

#[test]
fn container_discriminator_needs_no_interpretation_from_this_crate() {
    let container = Container::parse(HEADER_CONTAINER).expect("valid container");

    // This crate exposes the discriminator's raw bytes (including its own
    // CBOR head byte) and nothing more -- no namespace/hint parsing lives
    // here, that's an optional, Record-Type-interpretation-layer concern
    // (header.js in the Node prototype). Just confirm it's exactly the
    // 8-byte decentralized namespace value the fixture encodes (0x48 =
    // major type 2, length 8), split off correctly.
    assert_eq!(
        container.discriminator(),
        &[0x48, 0xa9, 0xd6, 0xe1, 0xf3, 0x0b, 0x7c, 0x44, 0x82]
    );

    // And the Records iterator starts from the *real* first Record,
    // completely unaffected by whatever the discriminator's own shape
    // was -- the same generic decoder, no discriminator-specific code
    // path in how Records themselves get routed and walked.
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
    assert!(!records[0].ignored);
    let ssid = find_value(records[0].map_bytes, 0).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"SSID");
}

#[test]
fn byte_string_type_id_routes_correctly() {
    let container = Container::parse(BYTE_STRING_TYPE_ID_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(!rec.ignored);
    match &rec.type_id() {
        Some(Key::ByteString(bytes)) => {
            assert_eq!(bytes, &[0xa7, 0xf9, 0x0b, 0x3c]);
        }
        other => panic!("expected ByteString type_id, got {:?}", other),
    }

    let payload = find_value(rec.map_bytes, 0).unwrap().unwrap();
    assert_eq!(
        read_definite_string(payload).unwrap(),
        b"decentralized payload"
    );
}

#[test]
fn backup_type_ids_are_accumulated_and_accessible() {
    let container = Container::parse(BACKUP_TYPE_ID_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(!rec.ignored);

    // Primary type ID is the uint
    assert_eq!(rec.type_id(), Some(Key::Uint(100)));
    // Backup type ID is the byte string
    let ids = rec.type_ids();
    assert_eq!(ids.len(), 2);
    match ids[1] {
        Key::ByteString(bytes) => assert_eq!(bytes, &[0xa7, 0xf9, 0x0b, 0x3c]),
        other => panic!("expected ByteString backup, got {:?}", other),
    }
}

#[test]
fn namespace_pairing_prefix_item_yields_the_nested_typeid_and_the_raw_namespace() {
    let container = Container::parse(NAMESPACE_PAIRING_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert!(!rec.ignored);

    // The pairing's second element becomes the routing typeId, exactly
    // as if it had been a bare prefix item -- routing doesn't care which
    // form produced it.
    assert_eq!(rec.type_id(), Some(Key::Uint(1)));

    // The pairing's first element is exposed raw, uninterpreted -- this
    // crate doesn't know it's "a namespace," just that it came from a
    // recognized 2-element array shape.
    match rec.local_namespace() {
        Some(Key::ByteString(bytes)) => assert_eq!(bytes, &[0xcd, 0xcd, 0xcd, 0xcd]),
        other => panic!("expected ByteString local_namespace, got {:?}", other),
    }
}

#[test]
fn namespace_pairing_accepts_an_allocated_uint_namespace_too() {
    let container =
        Container::parse(ALLOCATED_NAMESPACE_PAIRING_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);
    assert_eq!(rec.type_id(), Some(Key::Uint(1)));
    assert_eq!(rec.local_namespace(), Some(Key::Uint(100)));
}

#[test]
fn a_record_with_no_pairing_item_has_no_local_namespace() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records[0].local_namespace(), None);
}

#[test]
fn a_namespace_pairing_primary_still_accumulates_an_ordinary_backup_typeid() {
    let container =
        Container::parse(NAMESPACE_PAIRING_WITH_BACKUP_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.ignored);

    assert_eq!(rec.type_id(), Some(Key::Uint(1)));
    match rec.local_namespace() {
        Some(Key::ByteString(bytes)) => assert_eq!(bytes, &[0xcd, 0xcd, 0xcd, 0xcd]),
        other => panic!("expected ByteString local_namespace, got {:?}", other),
    }

    let ids = rec.type_ids();
    assert_eq!(ids.len(), 2);
    match ids[1] {
        Key::ByteString(bytes) => assert_eq!(bytes, &[0xa7, 0xf9, 0x0b, 0x3c]),
        other => panic!("expected ByteString backup, got {:?}", other),
    }
}

// ---------------------------------------------------------------------
// Negative-integer map keys. CBOR permits them generally and QDEF's spec
// never explicitly restricted map keys to non-negative uints; before the
// `cbor::Key::NegInt` fix, `read_key` hard-errored (`NotAKey`) on any
// negint key, and because `Records::next` treats a `parse_record` error
// as unrecoverable (it can't know where a malformed item ends, so it
// can't safely resume), that single unhandled key killed decoding of
// every *subsequent* Record in the same Sequence too -- not just the one
// Record that had it. Bytes generated from the Node prototype (which
// already accepted negative keys silently) via an inline script, not
// `gen-rust-fixtures.js`, since this is EXPERIMENTAL and not part of the
// committed fixture set. See docs/FINDINGS.md.
// ---------------------------------------------------------------------

/// typeId(100) + { 0: "SSID", -1: "wifi-record-1" }
const RECORD_WITH_NEG_KEY: &[u8] = &[
    0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x20, 0x6d, 0x77, 0x69, 0x66, 0x69,
    0x2d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2d, 0x31,
];

/// RECORD_WITH_NEG_KEY immediately followed by a second, ordinary Record
/// (typeId(200) + { 0: "second" }) -- proves the Sequence survives past
/// the negative-keyed Record, not just that Record in isolation.
const TWO_RECORD_SEQ_WITH_NEG_KEY: &[u8] = &[
    0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x20, 0x6d, 0x77, 0x69, 0x66, 0x69,
    0x2d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2d, 0x31, 0x18, 0xc8, 0xa1, 0x00, 0x66, 0x73,
    0x65, 0x63, 0x6f, 0x6e, 0x64,
];

/// typeId(100) + { 0: "SSID", -2: "unknown" } -- an unrecognized EVEN
/// negative key, core-level-critical.
const RECORD_EVEN_NEG_KEY: &[u8] = &[
    0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x21, 0x67, 0x75, 0x6e, 0x6b, 0x6e,
    0x6f, 0x77, 0x6e,
];

/// typeId(100) + { 0: "SSID", -3: "unknown" } -- an unrecognized ODD
/// negative key, silently ignored at the core level.
const RECORD_ODD_NEG_KEY: &[u8] = &[
    0x18, 0x64, 0xa2, 0x00, 0x64, 0x53, 0x53, 0x49, 0x44, 0x22, 0x67, 0x75, 0x6e, 0x6b, 0x6e,
    0x6f, 0x77, 0x6e,
];

#[test]
fn a_negative_map_key_no_longer_hard_errors_the_whole_record() {
    let records: Vec<_> = records_from_sequence(RECORD_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records.len(), 1);
    assert!(!records[0].ignored);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
}

#[test]
fn a_negative_map_key_no_longer_kills_decoding_of_sibling_records_in_the_same_sequence() {
    // This is the regression this fix actually matters for: before
    // Key::NegInt existed, this returned only one Ok(record) followed by
    // an Err, because Records::next latches `done = true` on any
    // parse_record error and never resumes.
    let records: Vec<_> = records_from_sequence(TWO_RECORD_SEQ_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .expect("both records parse; a negint key must not abort the Sequence");
    assert_eq!(records.len(), 2);
    assert_eq!(records[0].type_id(), Some(Key::Uint(100)));
    assert_eq!(records[1].type_id(), Some(Key::Uint(200)));
}

#[test]
fn check_criticality_silently_skips_negative_keys_they_are_not_this_types_to_interpret() {
    let records: Vec<_> = records_from_sequence(RECORD_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    // WIFI_KNOWN_KEYS = &[0, 1, 2, 4]; it has no entry for -1, but that
    // must not matter -- check_criticality only ever looks at Key::Uint.
    let outcome = check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("the negative key must never reach a Type's on_ignored callback")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);
}

#[test]
fn extract_core_metadata_reads_the_reserved_external_id_key() {
    let records: Vec<_> = records_from_sequence(RECORD_WITH_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    let outcome = extract_core_metadata(records[0].map_bytes).unwrap();
    match outcome {
        CoreMetadataOutcome::Ok(meta) => {
            let raw = meta.external_id.expect("external_id present");
            assert_eq!(read_definite_string(raw).unwrap(), b"wifi-record-1");
        }
        other => panic!("expected Ok, got {:?}", other),
    }
}

#[test]
fn extract_core_metadata_aborts_on_an_unrecognized_even_negative_key() {
    let records: Vec<_> = records_from_sequence(RECORD_EVEN_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    let outcome = extract_core_metadata(records[0].map_bytes).unwrap();
    assert_eq!(outcome, CoreMetadataOutcome::Aborted(-2));
}

#[test]
fn extract_core_metadata_silently_ignores_an_unrecognized_odd_negative_key() {
    let records: Vec<_> = records_from_sequence(RECORD_ODD_NEG_KEY)
        .collect::<Result<_, _>>()
        .unwrap();
    let outcome = extract_core_metadata(records[0].map_bytes).unwrap();
    match outcome {
        CoreMetadataOutcome::Ok(meta) => assert_eq!(meta.external_id, None),
        other => panic!("expected Ok with no external_id, got {:?}", other),
    }
}
