//! Cross-validates this crate's independent, hand-rolled decoder against
//! containers encoded by the already round-trip-tested Node prototype (see
//! `fixtures.rs`, generated by `node prototype/scripts/gen-rust-fixtures.js`)
//! — catching the class of bug a single implementation checking itself
//! against itself never can.

use super::fixtures::*;
use super::*;

const WIFI_KNOWN_KEYS: &[u64] = &[0, 2, 3, 4, 6];

#[test]
fn wifi_record_routes_and_fields_extract() {
    let container = Container::parse(WIFI_CONTAINER).expect("valid container");
    assert_eq!(container.version, 1);

    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    let rec = &records[0];
    assert_eq!(rec.type_id, Some(100));
    assert!(!rec.aborted);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("no odd keys here")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let ssid = find_value(rec.map_bytes, 2).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"My Coffee Shop");
    let password = find_value(rec.map_bytes, 4).unwrap().unwrap();
    assert_eq!(read_definite_string(password).unwrap(), b"guest123");
}

#[test]
fn a_64_bit_class_private_use_type_id_decodes_correctly() {
    // §3.1's `0x10000`+ private-use-random tier needs the full uint64
    // range (§9 recommends 32- or 64-bit random values) — this crate's
    // `type_id: Option<u64>` already supports it, but proving it against
    // a fixture the Node encoder actually produced (not just an assumed
    // capability) is what caught a real bug in the *Node* prototype's
    // plain `cbor.encode()` path (docs/FINDINGS.md #14). The fixture here
    // uses u64::MAX specifically, the top of the range.
    let container = Container::parse(LARGE_TYPE_ID_CONTAINER).expect("valid container");
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 1);
    assert_eq!(records[0].type_id, Some(u64::MAX));
    assert!(!records[0].aborted);
}

#[test]
fn unrecognized_even_key_aborts_the_record() {
    let container = Container::parse(WIFI_UNKNOWN_EVEN_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.aborted); // routing itself succeeds; criticality is a separate, Record-Type-specific check

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |_| {
        panic!("must not reach an odd key")
    })
    .unwrap();
    assert_eq!(outcome, CriticalityOutcome::Aborted(8));
}

#[test]
fn unrecognized_odd_key_is_silently_ignored() {
    let container = Container::parse(WIFI_UNKNOWN_ODD_KEY_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];

    let mut ignored = Vec::new();
    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| ignored.push(k)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);
    assert_eq!(ignored, vec![9]);

    // Rest of the record is still fully usable.
    let ssid = find_value(rec.map_bytes, 2).unwrap().unwrap();
    assert_eq!(read_definite_string(ssid).unwrap(), b"SSID");
}

#[test]
fn a_tagged_item_is_malformed_input_not_an_alternate_route() {
    // Key 0 is the sole routing mechanism (§3.1) — an earlier draft also
    // routed via a CBOR tag equal to the Type ID, removed after finding it
    // collided with the IANA CBOR tag registry (FINDINGS.md #11-#12). A
    // CBOR-tagged item is no longer valid Record syntax: it's malformed,
    // Sequence-fatal input, not something to unwrap.
    let container = Container::parse(TAGGED_ITEM_IS_MALFORMED_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(result.err(), Some(Error::Cbor(cbor::Error::NotAMap)));
}

#[test]
fn missing_key_zero_aborts_at_routing_time() {
    let container = Container::parse(MISSING_KEY0_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(rec.aborted);
    assert_eq!(rec.abort_reason, Some(AbortReason::MissingKeyZero));
}

#[test]
fn one_aborted_record_does_not_affect_its_sibling() {
    let container = Container::parse(TWO_RECORD_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    assert_eq!(records.len(), 2);

    let first = check_criticality(records[0].map_bytes, WIFI_KNOWN_KEYS, |_| {}).unwrap();
    assert_eq!(first, CriticalityOutcome::Aborted(8));

    assert_eq!(records[1].type_id, Some(900));
    assert!(!records[1].aborted);
    let payload = find_value(records[1].map_bytes, 2).unwrap().unwrap();
    assert_eq!(read_definite_string(payload).unwrap(), b"sibling record");
}

#[test]
fn ndef_path_bare_sequence_with_no_magic_still_routes() {
    // Strip the 5-byte magic/version prefix and decode the bare CBOR
    // Sequence directly, simulating the NDEF MIME-typed path (§2).
    let bare_seq = &WIFI_CONTAINER[5..];
    assert!(
        Container::parse(bare_seq).is_err(),
        "must not look like a valid magic-prefixed container"
    );

    let records: Vec<_> = records_from_sequence(bare_seq)
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(records[0].type_id, Some(100));
}

#[test]
fn bad_magic_and_wrong_version_are_rejected() {
    let mut bad_magic = WIFI_CONTAINER.to_vec();
    bad_magic[0] = 0x00;
    assert_eq!(Container::parse(&bad_magic).err(), Some(Error::BadMagic));

    let mut bad_version = WIFI_CONTAINER.to_vec();
    bad_version[4] = 0x02;
    assert_eq!(
        Container::parse(&bad_version).err(),
        Some(Error::UnsupportedVersion(2))
    );
}

#[test]
fn field_value_shape_rule_rejects_a_bare_array_even_under_an_odd_optional_key() {
    // Key 11 is odd (optional) — without the field-value-shape rule, an
    // unrecognized odd key would just be silently ignored. It must instead
    // be rejected: the decoder can't determine this Record's byte length
    // without walking into the array's structure, which the rule forbids
    // it from ever attempting. This is a routing-time failure (the walker
    // can't even finish reading the map), not a criticality-check failure.
    let container = Container::parse(DISALLOWED_ARRAY_VALUE_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}

#[test]
fn structured_content_is_carried_as_an_opaque_byte_string_and_skips_at_zero_cost() {
    // The rule's *sanctioned* alternative: pre-encode the structured data
    // (here, a 2-element CBOR array of auth method names) and carry the
    // encoded bytes as a definite-length byte string under an ordinary
    // field key. The outer decoder never looks inside it — it's skip-safe
    // and round-trips byte-for-byte, exactly like any other opaque payload
    // (the same property Wrapper Records rely on in §4.1).
    let container = Container::parse(BYTE_STRING_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.aborted);

    // Odd/unrecognized key 11 doesn't trip criticality either — it's a
    // perfectly ordinary skip-safe byte-string value from the core's POV.
    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 11)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 11).unwrap().unwrap();
    let nested_cbor = read_definite_string(raw).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn tag_24_wrapping_a_definite_length_string_directly_is_a_legal_field_value() {
    // GitHub issue #8: tag 24 ("encoded CBOR data item") wrapping a
    // definite-length string directly is exactly as skip-safe as a bare
    // byte string — two fixed header reads instead of one, never a walk —
    // and gives generic CBOR tooling a marker that this field's bytes are
    // re-parseable, which a bare, unmarked byte string never can.
    let container = Container::parse(TAG24_WRAPPED_VALUE_CONTAINER).unwrap();
    let records: Vec<_> = container.records().collect::<Result<_, _>>().unwrap();
    let rec = &records[0];
    assert!(!rec.aborted);

    let outcome = check_criticality(rec.map_bytes, WIFI_KNOWN_KEYS, |k| assert_eq!(k, 11)).unwrap();
    assert_eq!(outcome, CriticalityOutcome::Ok);

    let raw = find_value(rec.map_bytes, 11).unwrap().unwrap();
    // find_value returns the *whole* value including the tag header — the
    // caller unwraps it, the same way it would unwrap any tag it chooses
    // to interpret. Tag 24 is always a 2-byte head (0xd8 0x18).
    assert_eq!(&raw[..2], &[0xd8, 0x18]);
    let nested_cbor = read_definite_string(&raw[2..]).unwrap();
    assert_eq!(nested_cbor, NESTED_AUTH_METHODS_CBOR);
}

#[test]
fn tag_24_directly_wrapping_another_tag_is_rejected_not_silently_walked() {
    // The bound that keeps this from reopening unbounded recursion: tag 24
    // MUST wrap a definite-length string *directly*. Here the outer tag
    // 24's immediately-following item is itself a tag (24 again), not a
    // string — genuinely different from a byte string whose own contents
    // happen to be tag-24'd (still allowed, since that's opaque to the
    // outer skip). This MUST fail the same way a bare array does, not be
    // silently accepted at whatever depth an adversarial encoder chooses.
    let container = Container::parse(NESTED_TAG24_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}

#[test]
fn only_tag_24_specifically_is_allowed_not_tags_generally() {
    // Tag 0 ("standard date/time string") wrapping a byte string is a
    // real, IANA-registered tag — still MUST be rejected, since it isn't
    // 24. Allowing any tag number to wrap a field value would reopen the
    // "private, per-application enumeration" hazard the old Smart-Route
    // tag mechanism was removed for (FINDINGS.md #11-#12); this keeps the
    // exception exactly as narrow as the one case that's actually
    // skip-safe *and* has a standardized, non-QDEF-specific meaning.
    let container = Container::parse(OTHER_TAG_WRAPPED_VALUE_CONTAINER).unwrap();
    let result: Result<Vec<_>, _> = container.records().collect();
    assert_eq!(
        result.err(),
        Some(Error::Cbor(cbor::Error::DisallowedFieldValueShape))
    );
}
